language: php

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

env:
  - CONTAO_VERSION=contao/core-bundle ~4.4.0
  - CONTAO_VERSION=contao/core-bundle ~4.5.0
  - CONTAO_VERSION=contao/core-bundle ~4.6.0

matrix:
  exclude:
    - php: 5.6
      env: CONTAO_VERSION=contao/core-bundle ~4.5.0
    - php: 7.0
      env: CONTAO_VERSION=contao/core-bundle ~4.5.0
    - php: 5.6
      env: CONTAO_VERSION=contao/core-bundle ~4.6.0
    - php: 7.0
      env: CONTAO_VERSION=contao/core-bundle ~4.6.0

sudo: false

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - travis_retry composer self-update && composer --version
  # We have to supply the branch alias here again as travis checks out a commit hash and therefore destroys the
  # circular dependency phpcq/all-tasks -> phpcq/autoload-validation -> phpcq/all-tasks.
  - >
    if [ "x${TRAVIS_TAG}" != "x" ]; then
      COMPOSER_ROOT_VERSION=${TRAVIS_TAG} travis_retry composer update --prefer-dist --no-interaction;
    else
      COMPOSER_ROOT_VERSION=$([[ ${TRAVIS_BRANCH} =~ hotfix/([0-9.]*(-(alpha|beta|rc)[0-9]+)?) ]] \
        && echo ${BASH_REMATCH[1]} \
        || echo dev-${TRAVIS_BRANCH}) \
        travis_retry composer update --prefer-dist --no-interaction;
    fi

script: ant -keep-going

git:
  depth: 2147483647

cache:
  directories:
    - vendor
